### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.List com.maddyhome.idea.vim.group.KeyGroup.getMapTo(com.maddyhome.idea.vim.command.MappingMode, java.util.List)'

### ISSUE THREAD

**Issue by danny-su** [dankinsoid/IdeaVimMulticursor#7]
```
java.lang.NoSuchMethodError: 'java.util.List com.maddyhome.idea.vim.group.KeyGroup.getMapTo(com.maddyhome.idea.vim.command.MappingMode, java.util.List)'
	at com.github.dankinsoid.multicursor.UtilsKt.map(Utils.kt:41)
	at com.github.dankinsoid.multicursor.IdeaVimMulticursor.init(IdeaVimMulticursor.kt:28)
	at com.maddyhome.idea.vim.extension.VimExtensionRegistrar.initExtension(VimExtensionRegistrar.kt:85)
	at com.maddyhome.idea.vim.extension.VimExtensionRegistrar.registerExtension$lambda$0(VimExtensionRegistrar.kt:69)
	at com.maddyhome.idea.vim.api.OptionListenersImpl.onGlobalOptionChanged(VimOptionGroupBase.kt:1427)
	at com.maddyhome.idea.vim.api.OptionListenersImpl.onEffectiveValueChanged(VimOptionGroupBase.kt:1413)
	at com.maddyhome.idea.vim.api.VimOptionGroupBase.doSetOptionValue(VimOptionGroupBase.kt:158)
	at com.maddyhome.idea.vim.api.VimOptionGroupBase.setOptionValue(VimOptionGroupBase.kt:122)
	at com.maddyhome.idea.vim.api.VimOptionGroupKt.setToggleOption(VimOptionGroup.kt:270)
	at com.maddyhome.idea.vim.vimscript.model.commands.SetCommandKt.parseOptionLine(SetCommand.kt:171)
	at com.maddyhome.idea.vim.vimscript.model.commands.SetCommandBase.processCommand(SetCommand.kt:72)
	at com.maddyhome.idea.vim.vimscript.model.commands.Command.runCommand(Command.kt:130)
	at com.maddyhome.idea.vim.vimscript.model.commands.Command.execute$lambda$1(Command.kt:105)
	at com.maddyhome.idea.vim.newapi.IjVimApplication.runReadAction$lambda$4(IjVimApplication.kt:74)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$4(AnyThreadWriteThreadingSupport.kt:260)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:272)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:260)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:858)
	at com.maddyhome.idea.vim.newapi.IjVimApplication.runReadAction(IjVimApplication.kt:74)
	at com.maddyhome.idea.vim.vimscript.model.commands.Command.execute(Command.kt:108)
	at com.maddyhome.idea.vim.api.VimScriptExecutorBase.execute(VimScriptExecutorBase.kt:40)
	at com.maddyhome.idea.vim.api.VimscriptExecutor.execute$default(VimscriptExecutor.kt:29)
	at com.maddyhome.idea.vim.api.VimScriptExecutorBase.executeFile(VimScriptExecutorBase.kt:96)
	at com.maddyhome.idea.vim.api.VimscriptExecutor.executeFile$default(VimscriptExecutor.kt:38)
	at com.maddyhome.idea.vim.vimscript.services.VimRcService.executeIdeaVimRc(VimRcService.kt:137)
	at com.maddyhome.idea.vim.VimPlugin.registerIdeavimrc(VimPlugin.java:287)
	at com.maddyhome.idea.vim.VimPlugin.turnOnPlugin(VimPlugin.java:341)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by dankinsoid** [comment]
@danny-su check update
